import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { LanguageProvider } from "@/contexts/LanguageContext";
import ScrollToTopButton from "@/components/ui/ScrollTopButton";
import Footer from "@/components/ui/Footer";
import { Noto_Sans_Balinese } from "next/font/google";
import ClientOnly from "@/components/base/ClientOnly";
// Import phông chữ
const notoSans = Noto_Sans_Balinese({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSans.variable} antialiased`}>
        {/* Chỉ dùng ThemeProvider bao ngoài khi bạn không cần nội dung trong server-render */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            {/* Các component sử dụng useTheme hoặc cần window phải đợi mount */}
            <ClientOnly>
              <Navbar />
              <ScrollToTopButton />
            </ClientOnly>
            {children}
            <Footer />
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
